[project]
name = "track-chair-review-tables"
version = "0.1.0"
description = "Produce summary tables of the different track reviews for use by the track chairs"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]

summary = """
python track-chair-review-tables.py
"""

[dependencies]
python = "3.12.*"
pandas = ">=2.2.1,<2.3"
jupyterlab = ">=4.1.6,<4.2"
jupytext = ">=1.16.1,<1.17"
